name: Nuget Release

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Download correct version fot .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.408
          
      # Preload all dependencies
      - name: Install dependencies
        run: dotnet restore
        
      # Build with Release configuration
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      # Ensure that packet works as expected
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      # Publish nuget to nuget.org
      - name: Publish nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Gcp.SecretManager.Provider/Gcp.SecretManager.Provider.csproj
          TAG_COMMIT: false
